Repository JUST-CLICK-BANK/fe-click-bank, pull requests merged in 2024-07, with the labels that each got.

#17 Design/friend list
  App.tsx
  assets/image/add.png
  assets/image/basicProfile.png
  assets/image/confirm.png
  assets/image/reject.png
  assets/image/search.png
  assets/image/search.svg
  assets/image/send.png
  page/friend/FriendList.tsx
Labels: publishing

#19 [Design] friend-request-list
  page/friend/FriendRequestList.tsx
Labels: publishing

#27 [Feat] AccountHistoryDetail 거래 내역 불러오기
  component/api/AccountHistoryApi.ts
  config/network.ts
  page/account-history/AccountHistoryDetail.tsx
Labels: feature

#39 [Design] friend-tab-navigator
  App.tsx
  assets/image/list.png
  page/friend/FriendList.tsx
  page/friend/FriendRequestList.tsx
  page/friend/FriendsComponent.tsx
Labels: publishing

#41 [Design] friend-search
  page/friend/FriendSearch.tsx
  page/friend/FriendsComponent.tsx
Labels: publishing

#42 [Feat] AccountHistoryDetail 페이지 메모 수정 & 전체 내역 조회 필터링
  App.tsx
  component/api/AccountHistoryApi.ts
  page/account-history/AccountHistory.tsx
  page/account-history/AccountHistoryDetail.tsx
Labels: feature

#47 [Design] friend-tab-navigator 수정
  page/friend/FriendSearch.tsx
  page/friend/FriendsComponent.tsx
Labels: publishing

#48 [Feat] AccountHistory 필터링
  page/account-history/AccountHistory.tsx
Labels: fix

#49 [Feat] Axios Header 수정
  config/network.ts
Labels: fix

#55 [Design] png -> svg
  page/friend/FriendSearch.tsx
  page/friend/FriendsComponent.tsx
Labels: publishing

#56 Feature/account history statistics
  App.tsx
  component/api/AccountHistoryApi.ts
  package.json
  page/account-history/AccountHistory.tsx
Labels: feature

#58 [Feat] AccountHistoryStatistics 페이지, 그래프 1차 구현
  page/account-history/AccountHistoryStatistics.tsx
Labels: feature

#59 [Feat] friend 서버 통신 (axios)
  page/friend/FriendSearch.tsx
  page/friend/FriendsComponent.tsx
  page/main/ClickHome.tsx
Labels: feature

#66 [Refactor] IP 변경 및 코드 수정
  page/friend/FriendSearch.tsx
  page/friend/FriendsComponent.tsx
Labels: bug, refactor

#74 [Feat] AccountHistoryStatistics 페이지 지출, 예산 통신 완료
  component/api/AccountHistoryApi.ts
  page/account-history/AccountHistory.tsx
  page/account-history/AccountHistoryDetail.tsx
  page/account-history/AccountHistoryStatistics.tsx
Labels: feature

#77 [Feat] 예산 수정 페이지 및 예산 수정 기능 구현
  component/account-history/BudgetUpdate.tsx
  component/api/AccountHistoryApi.ts
  page/account-history/AccountHistoryStatistics.tsx
Labels: feature

#82 [Fix] 카테고리 수정 기능 추가 및 수정
  component/api/AccountHistoryApi.ts
  config/network.ts
  page/account-history/AccountHistory.tsx
  page/account-history/AccountHistoryDetail.tsx
  page/account-history/AccountHistoryStatistics.tsx
Labels: feature, fix

#85 [Design] 내 친구 목록 퍼블리싱 수정
  page/friend/FriendsComponent.tsx
Labels: publishing

#94 친구 모임 통장 초대 조회/수락/거절
  page/friend/FriendInvite.tsx
  page/friend/FriendSearch.tsx
  page/friend/FriendsComponent.tsx
Labels: feature
