Repository JUST-CLICK-BANK/fe-click-bank, pull requests merged in 2024-08, with the labels that each got.

#97 [Feat] 내 카드 목록, 내 카드 정보, 카드 상품 목록, 카드 상품 정보 Get 요청 통신 완료
  component/api/CardListApi.ts
  config/network.ts
  page/card/AddCardList.tsx
  page/card/CardInformation.tsx
  page/card/CardList.tsx
  page/card/MyCard.tsx
Labels: feature

#110 Fix/account history
  App.tsx
  component/api/AccountHistoryApi.ts
  config/network.ts
  package-lock.json
  page/account-history/AccountHistory.tsx
  page/account-history/AccountHistoryDetail.tsx
  page/payment/LoginCheck.tsx
  page/payment/Payment.tsx
  yarn.lock
Labels: fix

#119 Fix/account history
  component/api/AccountHistoryApi.ts
  page/account-history/AccountHistory.tsx
  page/account-history/AccountHistoryDetail.tsx
  page/account-history/AccountHistoryStatistics.tsx
Labels: feature

#121 친구 컴포넌트 분리 및 수정
  App.tsx
  component/bottom-bar/Bottom.tsx
  page/friend/FriendInvite.tsx
  page/friend/FriendList.tsx
  page/friend/FriendRequestList.tsx
  page/friend/FriendSearch.tsx
  page/friend/FriendsComponent.tsx
  page/friend/MyFriend.tsx
Labels: refactor

#125 [Feat] 친구 송금 서비스 구현
  page/friend/FriendList.tsx
  page/friend/MyFriend.tsx
Labels: feature

#129 [Fix] 거래내역 순서 정렬 수정
  page/account-history/AccountHistory.tsx
Labels: fix

#133 [Feat] 거래 내역 Pull To Refresh 기능 추가
  page/account-history/AccountHistory.tsx
  page/account-history/AccountHistoryStatistics.tsx
Labels: feature

#138 [Feat] 내 친구 검색
  page/friend/FriendInvite.tsx
  page/friend/FriendList.tsx
  page/friend/MyFriendSearch.tsx
Labels: feature

#142 [Fix] 버그 수정
  component/api/AccountHistoryApi.ts
  config/network.ts
  page/account-history/AccountHistoryDetail.tsx
  page/account-history/AccountHistoryStatistics.tsx
Labels: fix

#144 [Fix] 버그 수정
  page/account-history/AccountHistoryDetail.tsx
Labels: fix

#146 [Fix] 거래 내역 순서 버그 수정
  page/account-history/AccountHistory.tsx
Labels: fix

#147 [Fix] 분석 - 카테고리 % 추가
  page/account-history/AccountHistoryStatistics.tsx
Labels: fix
